export const actionTypes = {
  SIGNUP: "signup - user",
  RESTORE_USER: "RESTORE - USER",
  SET_PRIZE_FOR_USER: "SET_PRIZE_FOR_USER",
  TOOGLE_ADD_CONTACT_AVAIABLE: "TOOGLE_ADD_CONTACT_AVAIABLE",
  SELECT_CONTACT: "SELECT_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  UPDATE_PRIZE_FOR_CONTACT: "UPDATE_PRIZE_FOR_CONTACT",
  SET_PRIZE: "SET_PRIZE",
  DELETE_PRIZE: "DELETE_PRIZE",
  DELETE_PRIZE_BY_FIELD_ID: "DELETE_PRIZE_BY_FIELD_ID",
  UPDATE_PRIZE: "UPDATE_PRIZE",
  SET_FIELDS: "SET_FIELDS",
  TOGGLE_VALIDATE_IN_PROCESS: "SET_CHECKOUT_IN_PROCESS",
  RESET_NUEVA_RECARGA_STATE: "RESET_NUEVA_RECARGA_STATE",
  RESTORE_NUEVA_RECARGA_INITIAL_STATE: "RESTORE_NUEVA_RECARGA_INITIAL_STATE"
};
