export const actionTypes = {
  // user
  SIGNUP: "signup - user",
  RESTORE_USER: "RESTORE - USER",
  SET_PRIZE_FOR_USER: "SET_PRIZE_FOR_USER",
  SET_COUNTRY_FOR_USER: "SET COUNTRY FOR USER",
  SET_OPERATOR_FOR_USER: "SET_OPERATOR_FOR_USER",
  SET_IDIOMA: "SET_IDIOMA",

  // nueva recarga
  TOOGLE_ADD_CONTACT_AVAIABLE: "TOOGLE_ADD_CONTACT_AVAIABLE",
  SELECT_CONTACT: "SELECT_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  DELETE_ALL_CONTACTS: "DELETE ALL CONTACTS",
  UPDATE_PRIZE_FOR_CONTACT: "UPDATE_PRIZE_FOR_CONTACT",
  SET_PRIZE: "SET_PRIZE",
  DELETE_PRIZE: "DELETE_PRIZE",
  DELETE_PRIZE_BY_FIELD_ID: "DELETE_PRIZE_BY_FIELD_ID",
  UPDATE_PRIZE: "UPDATE_PRIZE",
  SET_FIELDS: "SET_FIELDS",
  TOGGLE_VALIDATE_IN_PROCESS: "SET_CHECKOUT_IN_PROCESS",
  RESET_NUEVA_RECARGA_STATE: "RESET_NUEVA_RECARGA_STATE",
  RESTORE_NUEVA_RECARGA_INITIAL_STATE: "RESTORE_NUEVA_RECARGA_INITIAL_STATE",
  DELETE_FIELD: "DELETE_FIELD",
  DELETE_ALL_FIELDS: "DELETE ALL FIELDS",
  DELETE_ALL_VALIDATED_PRIZES: "DELETE_ALL_VALIDATED_PRIZES",
  SET_TRANSACTIONS_ID_ARRAY: "SET_TRANSACTIONS_ID_ARRAY",
  SET_PAYMENT_PRICE_USD: "SET_PAYMENT_PRICE_USD",
  SET_PAYMENT_INTENT_ID: "SET_PAYMENT_INTENT_ID",
  SET_HAY_PREMIO_COBRADO_MODAL: "SET_HAY_PREMIO_COBRADO_MODAL",
  SET_HAY_PREMIO_FALLIDO_MODAL: "SET_HAY_PREMIO_FALLIDO_MODAL",

  // socket
  SET_SOCKET_ID: "SET_SOCKET_ID",
  SET_TRANSACCIONES_NORMALES_ESPERADAS: "SET_TRANSACCIONES_NORMALES_ESPERADAS",
  SET_TRANSACCIONES_PREMIO_ESPERADAS: "SET_TRANSACCIONES_PREMIO_ESPERADAS",
  SET_TRANSACCION_NORMAL_FALLIDA: "SET_TRANSACCION_NORMAL_FALLIDA",
  SET_TRANSACCION_PREMIO_FALLIDA: "SET_TRANSACCION_PREMIO_FALLIDA",
  SET_NEW_TRANSACCION_NORMAL_COMPLETADA:
    "SET_NEW_TRANSACCION_NORMAL_COMPLETADA",
  SET_NEW_TRANSACCION_PREMIO_COMPLETADA:
    "SET_NEW_TRANSACCION_PREMIO_COMPLETADA",
  RESET_SOCKET_STATE: "RESET_SOCKET_STATE",

  // interface
  SET_SHOW_EXPIRED_PRIZE: "SET_SHOW_EXPIRED_PRIZE",
  SET_SHOW_INVISIBLE_LOAD_DATA: "SET_SHOW_INVISIBLE_LOAD_DATA",
};
