export const actionTypes = {
  SIGNUP: "signup - user",
  RESTORE_USER: "RESTORE - USER",
  SET_PRIZE: "SET_PRIZE",
  TOOGLE_ADD_CONTACT_AVAIABLE: "TOOGLE_ADD_CONTACT_AVAIABLE",
  SELECT_CONTACT: "SELECT_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT"
};
